//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_PR_AV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrito
    {
        public int IdCarrito { get; set; }
        public int cantidad { get; set; }
        public Nullable<int> facturaId { get; set; }
        public Nullable<int> productoId { get; set; }
        public Nullable<int> usuarioId { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
