//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_PR_AV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagen
    {
        public int IdImagen { get; set; }
        public byte[] imagen1 { get; set; }
        public Nullable<int> productoId { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
